const SUBMIT_ARTIST = 1;
const UPDATE_ARTIST = 2;
const DELETE_ARTIST = 3;
const EDIT_ARTIST = 4;
const RESET_ARTIST = 5;
const SET_LOADING = 6;
const INPUT_ARTIST = 7;
const FETCH_COMPLETE = 8;
const SEARCH_ARTIST = 9;
const IMAGE_ARTIST = 10;

export { IMAGE_ARTIST, SUBMIT_ARTIST, UPDATE_ARTIST, DELETE_ARTIST, EDIT_ARTIST, RESET_ARTIST, SET_LOADING, INPUT_ARTIST, FETCH_COMPLETE, SEARCH_ARTIST };