const CREATE_ARTIST = 1;
const UPDATE_ARTIST = 2;
const DELETE_ARTIST = 3;
const EDIT_BUTTON = 4;
const RESET_FORM = 5;
const SET_LOADING = 6;
const FETCH_COMPLETE = 7;
const HANDLE_INPUT = 8;
const SUBMIT_COMPLETE = 9;
const HANDLE_IMAGE = 10;

export {
    CREATE_ARTIST, UPDATE_ARTIST, DELETE_ARTIST, EDIT_BUTTON, RESET_FORM, SET_LOADING, FETCH_COMPLETE, HANDLE_INPUT, SUBMIT_COMPLETE, HANDLE_IMAGE
}