const SUBMIT_COMPLETE = 1;
const UPDATE_GENRE = 2;
const DELETE_GENRE = 3;
const EDIT_BUTTON = 4;
const RESET_FORM = 5;
const SET_LOADING = 6;
const FETCH_COMPLETE = 7;
const SEARCH_GENRE = 8;
const INPUT_GENRE = 9;

export {
    INPUT_GENRE, SEARCH_GENRE, SUBMIT_COMPLETE, UPDATE_GENRE, DELETE_GENRE, EDIT_BUTTON, RESET_FORM, SET_LOADING, FETCH_COMPLETE
}