const SUBMIT_ALBUM = 1;
const UPDATE_ALBUM = 2;
const DELETE_ALBUM = 3;
const EDIT_ALBUM = 4;
const RESET_ALBUM = 5;
const SET_LOADING = 6;
const INPUT_ALBUM = 7;
const FETCH_COMPLETE = 8;
const SEARCH_ALBUM = 9;
const IMAGE_ALBUM = 10;

export { IMAGE_ALBUM, SUBMIT_ALBUM, UPDATE_ALBUM, DELETE_ALBUM, EDIT_ALBUM, RESET_ALBUM, SET_LOADING, INPUT_ALBUM, FETCH_COMPLETE, SEARCH_ALBUM };